export const WANT_PURCHASE_REQUEST = 'WANT_PURCHASE_REQUEST';
export const WANT_PURCHASE_SUCCESS = 'WANT_PURCHASE_SUCCESS';
export const WANT_PURCHASE_FAIL = 'WANT_PURCHASE_FAIL';

export const COUNT_WANT_PURCHASE_REQUEST = 'COUNT_WANT_PURCHASE_REQUEST';
export const COUNT_WANT_PURCHASE_SUCCESS = 'COUNT_WANT_PURCHASE_SUCCESS';
export const COUNT_WANT_PURCHASE_FAIL = 'COUNT_WANT_PURCHASE_FAIL';

export const EXCHANGE_REQUEST = 'EXCHANGE_REQUEST';
export const EXCHANGE_SUCCESS = 'EXCHANGE_SUCCESS';
export const EXCHANGE_FAIL = 'EXCHANGE_FAIL';

export const WANT_SELL_REQUEST = 'WANT_SELL_REQUEST';
export const WANT_SELL_SUCCESS = 'WANT_SELL_SUCCESS';
export const WANT_SELL_FAIL = 'WANT_SELL_FAIL';

export const COUNT_WANT_SELL_REQUEST = 'COUNT_WANT_SELL_REQUEST';
export const COUNT_WANT_SELL_SUCCESS = 'COUNT_WANT_SELL_SUCCESS';
export const COUNT_WANT_SELL_FAIL = 'COUNT_WANT_SELL_FAIL';

export const ACCEPT_EXCHANGE_REQUEST = 'ACCEPT_EXCHANGE_REQUEST';
export const ACCEPT_EXCHANGE_SUCCESS = 'ACCEPT_EXCHANGE_SUCCESS';
export const ACCEPT_EXCHANGE_FAIL = 'ACCEPT_EXCHANGE_FAIL';

export const CANCEL_EXCHANGE_REQUEST = 'CANCEL_EXCHANGE_REQUEST';
export const CANCEL_EXCHANGE_SUCCESS = 'CANCEL_EXCHANGE_SUCCESS';
export const CANCEL_EXCHANGE_FAIL = 'CANCEL_EXCHANGE_FAIL';

export const RESET_EXCHANGE_TYPE = 'RESET_EXCHANGE_TYPE';
