export const WANT_PURCHASE_REQUEST = 'WANT_PURCHASE_REQUEST';
export const WANT_PURCHASE_SUCCESS = 'WANT_PURCHASE_SUCCESS';
export const WANT_PURCHASE_FAIL = 'WANT_PURCHASE_FAIL';

export const WANT_SELL_REQUEST = 'WANT_SELL_REQUEST';
export const WANT_SELL_SUCCESS = 'WANT_SELL_SUCCESS';
export const WANT_SELL_FAIL = 'WANT_SELL_FAIL';

export const RESET_EXCHANGE_TYPE = 'RESET_EXCHANGE_TYPE';
