export const MAPPING_LIST_REQUEST = 'MAPPING_LIST_REQUEST';
export const MAPPING_LIST_SUCCESS = 'MAPPING_LIST_SUCCESS';
export const MAPPING_LIST_FAIL = 'MAPPING_LIST_FAIL';

export const SUGGEST_LIST_REQUEST = 'SUGGEST_LIST_REQUEST';
export const SUGGEST_LIST_SUCCESS = 'SUGGEST_LIST_SUCCESS';
export const SUGGEST_LIST_FAIL = 'SUGGEST_LIST_FAIL';

export const JOIN_EXCHANGE_REQUEST = 'JOIN_EXCHANGE_REQUEST';
export const JOIN_EXCHANGE_SUCCESS = 'JOIN_EXCHANGE_SUCCESS';
export const JOIN_EXCHANGE_FAIL = 'JOIN_EXCHANGE_FAIL';

export const CANCEL_JOIN_EXCHANGE_REQUEST = 'CANCEL_JOIN_EXCHANGE_REQUEST';
export const CANCEL_JOIN_EXCHANGE_SUCCESS = 'CANCEL_JOIN_EXCHANGE_SUCCESS';
export const CANCEL_JOIN_EXCHANGE_FAIL = 'CANCEL_JOIN_EXCHANGE_FAIL';

export const SELL_REFUND_REQUEST = 'SELL_REFUND_REQUEST';
export const SELL_REFUND_SUCCESS = 'SELL_REFUND_SUCCESS';
export const SELL_REFUND_FAIL = 'SELL_REFUND_FAIL';

export const COUNT_SELL_REFUND = 'COUNT_SELL_REFUND';
export const COUNT_SELL_REFUND_SUCCESS = 'COUNT_SELL_REFUND_SUCCESS';
export const COUNT_SELL_REFUND_FAIL = 'COUNT_SELL_REFUND_FAIL';

export const RESET_MAPPING = 'RESET_MAPPING';
