export const MAPPING_LIST_REQUEST = 'MAPPING_LIST_REQUEST';
export const MAPPING_LIST_SUCCESS = 'MAPPING_LIST_SUCCESS';
export const MAPPING_LIST_FAIL = 'MAPPING_LIST_FAIL';

export const RESET_MAPPING = 'RESET_MAPPING';
