export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST';
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS';
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL';
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST';
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS';
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL';
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET';

export const PURCHASE_REQUEST = 'PURCHASE_REQUEST';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';

export const COUNT_PURCHASE = 'COUNT_PURCHASE';
export const COUNT_PURCHASE_SUCCESS = 'COUNT_PURCHASE_SUCCESS';
export const COUNT_PURCHASE_FAIL = 'COUNT_PURCHASE_FAIL';

export const COMPLETE_DELIVERY_REQUEST = 'COMPLETE_DELIVERY_REQUEST';
export const COMPLETE_DELIVERY_SUCCESS = 'COMPLETE_DELIVERY_SUCCESS';
export const COMPLETE_DELIVERY_FAIL = 'COMPLETE_DELIVERY_FAIL';

export const COUNT_COMPLETE_DELIVERY = 'COUNT_COMPLETE_DELIVERY';
export const COUNT_COMPLETE_DELIVERY_SUCCESS =
  'COUNT_COMPLETE_DELIVERY_SUCCESS';
export const COUNT_COMPLETE_DELIVERY_FAIL = 'COUNT_COMPLETE_DELIVERY_FAIL';

export const CANCELLED_REQUEST = 'CANCELLED_REQUEST';
export const CANCELLED_SUCCESS = 'CANCELLED_SUCCESS';
export const CANCELLED_FAIL = 'CANCELLED_FAIL';

export const COUNT_CANCELLED = 'COUNT_CANCELLED';
export const COUNT_CANCELLED_SUCCESS = 'COUNT_CANCELLED_SUCCESS';
export const COUNT_CANCELLED_FAIL = 'COUNT_CANCELLED_FAIL';

export const SELL_COMPLETE_DELIVERY = 'SELL_COMPLETE_DELIVERY';
export const SELL_COMPLETE_DELIVERY_SUCCESS = 'SELL_COMPLETE_DELIVERY_SUCCESS';
export const SELL_COMPLETE_DELIVERY_FAIL = 'SELL_COMPLETE_DELIVERY_FAIL';

export const COUNT_SELL_COMPLETE_DELIVERY = 'COUNT_SELL_COMPLETE_DELIVERY';
export const COUNT_SELL_COMPLETE_DELIVERY_SUCCESS =
  'COUNT_SELL_COMPLETE_DELIVERY_SUCCESS';
export const COUNT_SELL_COMPLETE_DELIVERY_FAIL =
  'COUNT_SELL_COMPLETE_DELIVERY_FAIL';

export const SELL_CANCELLED_REQUEST = 'SELL_CANCELLED_REQUEST';
export const SELL_CANCELLED_SUCCESS = 'SELL_CANCELLED_SUCCESS';
export const SELL_CANCELLED_FAIL = 'SELL_CANCELLED_FAIL';

export const COUNT_SELL_CANCELLED = 'COUNT_SELL_CANCELLED';
export const COUNT_SELL_CANCELLED_SUCCESS = 'COUNT_SELL_CANCELLED_SUCCESS';
export const COUNT_SELL_CANCELLED_FAIL = 'COUNT_SELL_CANCELLED_FAIL';

export const COUNT_SELL = 'COUNT_SELL';
export const COUNT_SELL_SUCCESS = 'COUNT_SELL_SUCCESS';
export const COUNT_SELL_FAIL = 'COUNT_SELL_FAIL';

export const WAITING_DELIVERY_REQUEST = 'WAITING_DELIVERY_REQUEST';
export const WAITING_DELIVERY_SUCCESS = 'WAITING_DELIVERY_SUCCESS';
export const WAITING_DELIVERY_FAIL = 'WAITING_DELIVERY_FAIL';

export const COUNT_WAITING_DELIVERY = 'COUNT_WAITING_DELIVERY';
export const COUNT_WAITING_DELIVERY_SUCCESS = 'COUNT_WAITING_DELIVERY_SUCCESS';
export const COUNT_WAITING_DELIVERY_FAIL = 'COUNT_WAITING_DELIVERY_FAIL';

export const DELIVERY_REQUEST = 'DELIVERY_REQUEST';
export const DELIVERY_SUCCESS = 'DELIVERY_SUCCESS';
export const DELIVERY_FAIL = 'DELIVERY_FAIL';

export const SELL_DELIVERY_REQUEST = 'SELL_DELIVERY_REQUEST';
export const SELL_DELIVERY_SUCCESS = 'SELL_DELIVERY_SUCCESS';
export const SELL_DELIVERY_FAIL = 'SELL_DELIVERY_FAIL';

export const SELL_COUNT_DELIVERY = 'SELL_COUNT_DELIVERY';
export const SELL_COUNT_DELIVERY_SUCCESS = 'SELL_COUNT_DELIVERY_SUCCESS';
export const SELL_COUNT_DELIVERY_FAIL = 'SELL_COUNT_DELIVERY_FAIL';

export const COUNT_DELIVERY = 'COUNT_DELIVERY';
export const COUNT_DELIVERY_SUCCESS = 'COUNT_DELIVERY_SUCCESS';
export const COUNT_DELIVERY_FAIL = 'COUNT_DELIVERY_FAIL';

export const DELIVERY_INFO_REQUEST = 'DELIVERY_INFO_REQUEST';
export const DELIVERY_INFO_SUCCESS = 'DELIVERY_INFO_SUCCESS';
export const DELIVERY_INFO_FAIL = 'DELIVERY_INFO_FAIL';

export const SELL_REQUEST = 'SELL_REQUEST';
export const SELL_SUCCESS = 'SELL_SUCCESS';
export const SELL_FAIL = 'SELL_FAIL';

export const SELL_WAITING_DELIVERY = 'SELL_WAITING_DELIVERY';
export const SELL_WAITING_DELIVERY_SUCCESS = 'SELL_WAITING_DELIVERY_SUCCESS';
export const SELL_WAITING_DELIVERY_FAIL = 'SELL_WAITING_DELIVERY_FAIL';

export const COUNT_SELL_WAITING_DELIVERY = 'COUNT_SELL_WAITING_DELIVERY';
export const COUNT_SELL_WAITING_DELIVERY_SUCCESS =
  'COUNT_SELL_WAITING_DELIVERY_SUCCESS';
export const COUNT_SELL_WAITING_DELIVERY_FAIL =
  'COUNT_SELL_WAITING_DELIVERY_FAIL';

export const ACCEPT_ORDER_REQUEST = 'ACCEPT_ORDER_REQUEST';
export const ACCEPT_ORDER_SUCCESS = 'ACCEPT_ORDER_SUCCESS';
export const ACCEPT_ORDER_FAIL = 'ACCEPT_ORDER_FAIL';

export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAIL = 'CANCEL_ORDER_FAIL';

export const RECEIVE_PRODUCT_REQUEST = 'RECEIVE_PRODUCT_REQUEST';
export const RECEIVE_PRODUCT_SUCCESS = 'RECEIVE_PRODUCT_SUCCESS';
export const RECEIVE_PRODUCT_FAIL = 'RECEIVE_PRODUCT_FAIL';

export const REFUND_PRODUCT_REQUEST = 'REFUND_PRODUCT_REQUEST';
export const REFUND_PRODUCT_SUCCESS = 'REFUND_PRODUCT_SUCCESS';
export const REFUND_PRODUCT_FAIL = 'REFUND_PRODUCT_FAIL';

export const GET_REFUND_REQUEST = 'GET_REFUND_REQUEST';
export const GET_REFUND_SUCCESS = 'GET_REFUND_SUCCESS';
export const GET_REFUND_FAIL = 'GET_REFUND_FAIL';

export const COUNT_REFUND_REQUEST = 'COUNT_REFUND_REQUEST';
export const COUNT_REFUND_REQUEST_SUCCESS = 'COUNT_REFUND_REQUEST_SUCCESS';
export const COUNT_REFUND_REQUEST_FAIL = 'COUNT_REFUND_REQUEST_FAIL';

export const ACCEPT_REFUND_REQUEST = 'ACCEPT_REFUND_REQUEST';
export const ACCEPT_REFUND_SUCCESS = 'ACCEPT_REFUND_SUCCESS';
export const ACCEPT_REFUND_FAIL = 'ACCEPT_REFUND_FAIL';

export const CANCEL_REFUND_REQUEST = 'CANCEL_REFUND_REQUEST';
export const CANCEL_REFUND_SUCCESS = 'CANCEL_REFUND_SUCCESS';
export const CANCEL_REFUND_FAIL = 'CANCEL_REFUND_FAIL';

export const REPORT_ADMIN_REQUEST = 'REPORT_ADMIN_REQUEST';
export const REPORT_ADMIN_SUCCESS = 'REPORT_ADMIN_SUCCESS';
export const REPORT_ADMIN_FAIL = 'REPORT_ADMIN_FAIL';

export const RESET_ORDER_TYPE = 'RESET_ORDER_TYPE';
